### ISSUE TITLE
Rack menu « Library » wants a downgrade (bug ?)

### ISSUE THREAD

**Issue by zebulon-1st** [danieldavies99/DanielDaviesVCV#17]
System : Debian GNU/Linux 11 (bullseye)
$ uname -a : Linux debian-1 5.10.0-14-amd64 SMP Debian 5.10.113-1 (2022-04-29) x86_64 GNU/Linux

---
I did everything, as with other plugins to be compiled & installed (sorry if some outputs are in fr) :
```
Sources/Rack/plugins$ git clone https://github.com/danieldavies99/sequel.git
Clonage dans 'sequel'...
remote: Enumerating objects: 368, done.
remote: Counting objects: 100% (368/368), done.
remote: Compressing objects: 100% (133/133), done.
remote: Total 368 (delta 237), reused 350 (delta 235), pack-reused 0
Réception d'objets: 100% (368/368), 6.62 Mio | 9.80 Mio/s, fait.
Résolution des deltas: 100% (237/237), fait.
Sources/Rack/plugins$ cd sequel
Sources/Rack/plugins/sequel$ make -j8 && make install
...
```
(all one ok)

---
Then I add all your plugins from Rack Library web page.

Then I run Rack. A right mouse button show the all plugins panel. Yours appear first (sort = show last updated first).
But, the menu Library still shows "Daniel Davis   2.2.1 → 2.2.0". Wants downgrading ??? Strange.

And, of course, if we don't pay attention and click on this menu entry, your plugins have disappeared on next run.

Best regards.

**Comment by danieldavies99** [comment]
Thanks for bringing this to my attention, I'll look into it

**Comment by danieldavies99** [comment]
Apologies for leaving this so long, I'm going to close this issue as I haven't had any more reports of it happening, feel free to re-open it if you're still experiencing this.
