### ISSUE TITLE
Crashes on exit/delete of Sequel8/16 on Windows (again!)

### ISSUE THREAD

**Issue by SteveRussell33** [danieldavies99/DanielDaviesVCV#23]
Hi Daniel,
Having fixed this with the PRs you merged, I'm now getting the same crash report again.
```
#0  0x00007fff82fea4e3 in ntdll!RtlRegisterSecureMemoryCacheCallback () from C:\WINDOWS\SYSTEM32\ntdll.dll
#1  0x00007fff82fe6b6f in ntdll!RtlZeroHeap () from C:\WINDOWS\SYSTEM32\ntdll.dll
#2  0x00007fff82faceda in ntdll!memset () from C:\WINDOWS\SYSTEM32\ntdll.dll
#3  0x00007fff82fe9391 in ntdll!RtlRegisterSecureMemoryCacheCallback () from C:\WINDOWS\SYSTEM32\ntdll.dll
#4  0x00007fff82f15cc1 in ntdll!RtlGetCurrentServiceSessionId () from C:\WINDOWS\SYSTEM32\ntdll.dll
#5  0x00007fff82f15b74 in ntdll!RtlGetCurrentServiceSessionId () from C:\WINDOWS\SYSTEM32\ntdll.dll
#6  0x00007fff82f147b1 in ntdll!RtlFreeHeap () from C:\WINDOWS\SYSTEM32\ntdll.dll
#7  0x00007fff80f69c9c in msvcrt!free () from C:\WINDOWS\System32\msvcrt.dll
#8  0x00007fff431a0c60 in std::__new_allocator<short>::deallocate (this=<optimized out>, __p=0x7fff82f0ead2 <ntdll!RtlGetFullPathName_UstrEx+4674>, __n=59283)
    at C:/msys64/mingw64/include/c++/13.2.0/bits/new_allocator.h:168
#9  0x00007fff4319f67f in std::allocator_traits<std::allocator<short> >::deallocate (__n=59283, __p=0x7fff82f0ead2 <ntdll!RtlGetFullPathName_UstrEx+4674>, __a=...)
    at C:/msys64/mingw64/include/c++/13.2.0/bits/alloc_traits.h:515
#10 std::_Vector_base<short, std::allocator<short> >::_M_deallocate (__n=59283, __p=0x7fff82f0ead2 <ntdll!RtlGetFullPathName_UstrEx+4674>, this=0xfdd9378fdb540000)
    at C:/msys64/mingw64/include/c++/13.2.0/bits/stl_vector.h:387
#11 std::_Vector_base<short, std::allocator<short> >::~_Vector_base (this=0xfdd9378fdb540000, __in_chrg=<optimized out>)
    at C:/msys64/mingw64/include/c++/13.2.0/bits/stl_vector.h:366
#12 0x00007fff431a1e4d in std::vector<short, std::allocator<short> >::~vector (this=0xfdd9378fdb540000, this@entry=0x65d8820, __in_chrg=<optimized out>)
    at C:/msys64/mingw64/include/c++/13.2.0/bits/alloc_traits.h:944
#13 0x00007fff43184449 in SequelClockTracker::~SequelClockTracker (this=0x65d8800, __in_chrg=<optimized out>) at src/plugin.hpp:230
#14 0x00007fff431914a4 in Sequel8::~Sequel8 (this=this@entry=0x65d82d0, __in_chrg=<optimized out>) at src/Sequel8.cpp:6
#15 0x00007fff43191463 in Sequel8::~Sequel8 (this=0x65d82d0, __in_chrg=<optimized out>) at src/Sequel8.cpp:6
#16 0x00007fff4989a775 in rack::app::ModuleWidget::setModule (module=0x0, this=0x77d5620) at src/app/ModuleWidget.cpp:70
#17 rack::app::ModuleWidget::~ModuleWidget (this=this@entry=0x77d5620, __in_chrg=<optimized out>) at src/app/ModuleWidget.cpp:50
#18 0x00007fff43185b5d in Sequel8ModuleWidget::~Sequel8ModuleWidget (this=0x77d5620, __in_chrg=<optimized out>) at src/Sequel8.cpp:554
#19 Sequel8ModuleWidget::~Sequel8ModuleWidget (this=0x77d5620, __in_chrg=<optimized out>) at src/Sequel8.cpp:554
[snipped]
```
This log shows that there's a deallocation problem when the module's destructor is called either by deleting the module or exiting Rack.
This is what made me look at this the first time as I noticed that you had started working on your plugin again.
I thought my fix PRs had solved this but it seems they haven't and I don't get why. It's getting late where I am so I'm writing this out for you to take another look at and am more than happy to assist as I have a day off later.

The problem lies somewhere with the ``SequelClockTracker`` constructor and/or with the init of same in Sequel8/16.
https://github.com/danieldavies99/sequel/blob/16144ead5417d8d0b91a8f40481651895fa1b342/src/plugin.hpp#L232-L237
https://github.com/danieldavies99/sequel/blob/16144ead5417d8d0b91a8f40481651895fa1b342/src/Sequel8.cpp#L261
https://github.com/danieldavies99/sequel/blob/16144ead5417d8d0b91a8f40481651895fa1b342/src/Sequel16.cpp#L405
You have a default value for ``numRows`` but not for ``initializeNumSteps`` This is normally OK as in this case both modules are using this same user type, i.e. Sequel8 wants 8 steps on 3 rows and Sequel16 wants 16 steps on 3 rows.
I don't understand why the code doesn't work at runtime. I'm wondering if it's something to do with the constructor initialization list...

Thoughts?

**Comment by danieldavies99** [comment]
Hi Steve, after sleeping on it, I attacked it again this morning and was able to fix the issues, see PR: https://github.com/danieldavies99/sequel/pull/24

I've left some comments to try and explain what was going on, I think the error was quite misleading based on what the fix ended up looking like.
