### ISSUE TITLE
Samuel only accepting letters and numbers, no dot or dash

### ISSUE THREAD

**Issue by fractalgee** [danieldavies99/DanielDaviesVCV#30]
Given this is a morse code based thing, I was surprised that the dot and dash cannot be input, even though their length can be set.  MacOS 13.5, M1 Mini, standard PC keyboard which the mac sees fine, and all keys map to what it expects.. Any non-letter printable characters  (/, !, @, #, etc. pp.) also do not input, generates numbers though. Dash and dot input nothing, cursor does not advance, so does not recognize them.

**Comment by danieldavies99** [comment]
This is intended behaviour, the knobs for dot and dash length do not refer to dot/dash input characters.

Any alphanumeric text that you input is converted into dots and dashes behind the scenes based on morse code. Please see the manual for more info.

**Comment by fractalgee** [comment]
Misconception of me thinking I could input morse code. Thanks for edification, and the RTFM ;)

**Comment by danieldavies99** [comment]
> Misconception of me thinking I could input morse code. Thanks for edification, and the RTFM ;)

No probs! Hit me up on discord if you'd like me to run through it with you @dangerawaits
